name: Prod Release

on:
  push:
    tags:
      - "prod-[0-9]+"

permissions:
  id-token: write
  contents: write

env:
  STAGE: prod
  BRANCH: main
  AMPLIFY_APP_ID: ${{ secrets.PROD_AMPLIFY_APP_ID }}
  DEPLOY_WEBHOOK_URL: ${{ secrets.PROD_DEPLOY_WEBHOOK_URL }}

jobs:
  deploy:
    name: Deploy to AWS Amplify
    runs-on: ubuntu-latest
    env:
      GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 10

      - name: Load Environment Variables
        uses: ./.github/actions/setvars
        with:
          stage: ${{ env.STAGE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: no

      - name: Dispatch Deployment
        run: |
          LATEST_JOB=$(aws amplify list-jobs --app-id d1iugfuik6369 --branch-name main | jq -r '.jobSummaries[0].jobId')

          curl -X POST -d {} "${{ env.DEPLOY_WEBHOOK_URL }}" -H "Content-Type:application/json" -s

          ELAPSED=0
          CURRENT_JOB=$LATEST_JOB
          while [[ ("$LATEST_JOB" == "$CURRENT_JOB") && "$ELAPSED" -lt 600 ]]; do
            ELAPSED=$((ELAPSED+10))
            CURRENT_JOB=$(aws amplify list-jobs --app-id d1iugfuik6369 --branch-name main | jq -r '.jobSummaries[0].jobId')
            sleep 10
          done

      - name: Wait for Amplify to finish remote build
        run: |
          APP_ID=${{ env.AMPLIFY_APP_ID }}
          JOB_ID=$(aws amplify list-jobs --app-id d1iugfuik6369 --branch-name main | jq -r '.jobSummaries[0].jobId')

          # Run initial command to get the status
          STATUS="INIT"

          # Keep querying until status is RUNNING, PENDING, SUCCEED, or timeout after 10 minutes
          ELAPSED=0
          while [[ ("$STATUS" == "INIT" || "$STATUS" == "RUNNING" || "$STATUS" == "PENDING") && "$ELAPSED" -lt 600 ]]; do
            ELAPSED=$((ELAPSED+10))
            OUTPUT=$(aws amplify get-job --app-id $APP_ID --branch-name ${{ env.BRANCH }}) --job-id $JOB_ID | jq '.job')
            STATUS=$(echo $OUTPUT | jq -r '.summary.status')

            echo "Status: $STATUS"
            sleep 10
          done

          # Check final status and exit with appropriate code
          if [[ "$STATUS" == "SUCCEED" ]]; then
            echo "Status: SUCCEED"
            exit 0
          elif [[ "$STATUS" == "FAILED" ]]; then
            echo "Status: FAILED"
            exit 1
          else
            echo "Status: TIMEOUT"
            exit 1
          fi
